# Generated by Django 6.0.1 on 2026-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_notes_lesson_pdf_notes_remove_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, blank=True, null=True),
        ),
    ]
