# Generated by Django 6.0.1 on 2026-01-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_has_chosen_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_chosen_role',
        ),
    ]
